name: Deploy CV

on:
  push:
    branches: [main]
    paths:
      - 'cv/**'
  workflow_dispatch:


jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'
          cache-dependency-path: cv/package-lock.json

      - name: Install dependencies
        working-directory: cv
        run: npm ci

      - name: Build
        working-directory: cv
        run: npm run build

      - name: Clear remote directory
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_KEY }}
          script: rm -rf /var/www/personal-www/cv/*

      - name: Copy files to VPS
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_KEY }}
          source: cv/out/*
          target: /var/www/personal-www/cv
          strip_components: 2